/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import javax.swing.JButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Omar Ezzat
 */
public class BloodSugarView extends javax.swing.JFrame {

    /**
     * Creates new form BloodSugarView
     */
    public BloodSugarView() {
        initComponents();
        backToDashboardBtn.addActionListener(e -> setVisible(false));
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblCurrentReading = new javax.swing.JLabel();
        currentReadingField = new javax.swing.JTextField();
        lblPreviousReading = new javax.swing.JLabel();
        previousReadingField = new javax.swing.JTextField();
        lblTrendStatus = new javax.swing.JLabel();
        trendStatusField = new javax.swing.JTextField();
        lblRateTrend = new javax.swing.JLabel();
        rateTrendField = new javax.swing.JTextField();
        lblReadingHistory = new javax.swing.JLabel();
        scrollReadingHistory = new javax.swing.JScrollPane();
        readingHistoryArea = new javax.swing.JTextArea();
        backToDashboardBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Blood Sugar Details");
        setPreferredSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblTitle.setText("Blood Sugar Monitoring");
        getContentPane().add(lblTitle);
        lblTitle.setBounds(195, 37, 237, 25);

        lblCurrentReading.setText("Current Reading");
        getContentPane().add(lblCurrentReading);
        lblCurrentReading.setBounds(118, 89, 86, 34);

        currentReadingField.setEditable(false);
        currentReadingField.setText("0.00");
        getContentPane().add(currentReadingField);
        currentReadingField.setBounds(118, 135, 91, 31);

        lblPreviousReading.setText("Previous Reading");
        getContentPane().add(lblPreviousReading);
        lblPreviousReading.setBounds(118, 172, 91, 31);

        previousReadingField.setEditable(false);
        previousReadingField.setText("0.00");
        getContentPane().add(previousReadingField);
        previousReadingField.setBounds(118, 209, 91, 30);

        lblTrendStatus.setText("Trend Status");
        getContentPane().add(lblTrendStatus);
        lblTrendStatus.setBounds(370, 100, 103, 20);

        trendStatusField.setEditable(false);
        trendStatusField.setText("Unknown");
        trendStatusField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trendStatusFieldActionPerformed(evt);
            }
        });
        getContentPane().add(trendStatusField);
        trendStatusField.setBounds(373, 132, 88, 31);

        lblRateTrend.setText("Rate Trend");
        getContentPane().add(lblRateTrend);
        lblRateTrend.setBounds(373, 169, 231, 31);

        rateTrendField.setEditable(false);
        rateTrendField.setText("Unknown");
        getContentPane().add(rateTrendField);
        rateTrendField.setBounds(373, 206, 231, 33);

        lblReadingHistory.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblReadingHistory.setText("Reading History");
        getContentPane().add(lblReadingHistory);
        lblReadingHistory.setBounds(280, 250, 170, 30);

        readingHistoryArea.setEditable(false);
        readingHistoryArea.setColumns(20);
        readingHistoryArea.setLineWrap(true);
        readingHistoryArea.setRows(8);
        readingHistoryArea.setWrapStyleWord(true);
        scrollReadingHistory.setViewportView(readingHistoryArea);

        getContentPane().add(scrollReadingHistory);
        scrollReadingHistory.setBounds(90, 280, 520, 121);

        backToDashboardBtn.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        backToDashboardBtn.setText("Back to Dashboard");
        backToDashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToDashboardBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backToDashboardBtn);
        backToDashboardBtn.setBounds(210, 420, 282, 39);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void trendStatusFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trendStatusFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trendStatusFieldActionPerformed

    private void backToDashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToDashboardBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backToDashboardBtnActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToDashboardBtn;
    private javax.swing.JTextField currentReadingField;
    private javax.swing.JLabel lblCurrentReading;
    private javax.swing.JLabel lblPreviousReading;
    private javax.swing.JLabel lblRateTrend;
    private javax.swing.JLabel lblReadingHistory;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTrendStatus;
    private javax.swing.JTextField previousReadingField;
    private javax.swing.JTextField rateTrendField;
    private javax.swing.JTextArea readingHistoryArea;
    private javax.swing.JScrollPane scrollReadingHistory;
    private javax.swing.JTextField trendStatusField;
    // End of variables declaration//GEN-END:variables
   
    public void setCurrentReadingField(Float reading) {
        currentReadingField.setText(reading.toString());
    }

    public void setPreviousReadingField(Float previousReading) {
         previousReadingField.setText(previousReading.toString());
    }

    public void setTrendStatusField(String status) {
         trendStatusField.setText(status);
    }

    public void setRateTrendField(String rate) {
         rateTrendField.setText(rate);
    }

    public void setReadingHistoryArea(String message) {
         readingHistoryArea.append(message);
    }

    public JButton getBackToDashboardBtn() {
        return backToDashboardBtn;
    }
}
