/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import javax.swing.JButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Omar Ezzat
 */
public class BloodSugarView extends javax.swing.JFrame {

    /**
     * Creates new form BloodSugarView
     */
    public BloodSugarView() {
        initComponents();
        backToDashboardBtn.addActionListener(e -> setVisible(false));
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblCurrentReading = new javax.swing.JLabel();
        currentReadingField = new javax.swing.JTextField();
        lblPreviousReading = new javax.swing.JLabel();
        previousReadingField = new javax.swing.JTextField();
        lblTrendStatus = new javax.swing.JLabel();
        trendStatusField = new javax.swing.JTextField();
        lblRateTrend = new javax.swing.JLabel();
        rateTrendField = new javax.swing.JTextField();
        lblReadingHistory = new javax.swing.JLabel();
        scrollReadingHistory = new javax.swing.JScrollPane();
        readingHistoryArea = new javax.swing.JTextArea();
        backToDashboardBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Blood Sugar Details");
        setPreferredSize(new java.awt.Dimension(700, 500));
        setResizable(false);

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblTitle.setText("Blood Sugar Monitoring");

        lblCurrentReading.setText("Current Reading");

        currentReadingField.setEditable(false);
        currentReadingField.setText("0.00");

        lblPreviousReading.setText("Previous Reading");

        previousReadingField.setEditable(false);
        previousReadingField.setText("0.00");

        lblTrendStatus.setText("Trend Status");

        trendStatusField.setEditable(false);
        trendStatusField.setText("Unknown");
        trendStatusField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trendStatusFieldActionPerformed(evt);
            }
        });

        lblRateTrend.setText("Rate Trend");

        rateTrendField.setEditable(false);
        rateTrendField.setText("Unknown");

        lblReadingHistory.setText("Reading History");

        readingHistoryArea.setEditable(false);
        readingHistoryArea.setColumns(20);
        readingHistoryArea.setLineWrap(true);
        readingHistoryArea.setRows(8);
        readingHistoryArea.setWrapStyleWord(true);
        scrollReadingHistory.setViewportView(readingHistoryArea);

        backToDashboardBtn.setText("Back to Dashboard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPreviousReading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCurrentReading)
                    .addComponent(previousReadingField)
                    .addComponent(currentReadingField))
                .addGap(164, 164, 164)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRateTrend, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(rateTrendField)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(trendStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTrendStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(96, 96, 96))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(146, 146, 146))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(backToDashboardBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(scrollReadingHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblReadingHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(223, 223, 223))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCurrentReading, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(currentReadingField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPreviousReading, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(previousReadingField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblTrendStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(trendStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRateTrend, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rateTrendField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addComponent(lblReadingHistory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollReadingHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backToDashboardBtn)
                .addGap(78, 78, 78))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void trendStatusFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trendStatusFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trendStatusFieldActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToDashboardBtn;
    private javax.swing.JTextField currentReadingField;
    private javax.swing.JLabel lblCurrentReading;
    private javax.swing.JLabel lblPreviousReading;
    private javax.swing.JLabel lblRateTrend;
    private javax.swing.JLabel lblReadingHistory;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTrendStatus;
    private javax.swing.JTextField previousReadingField;
    private javax.swing.JTextField rateTrendField;
    private javax.swing.JTextArea readingHistoryArea;
    private javax.swing.JScrollPane scrollReadingHistory;
    private javax.swing.JTextField trendStatusField;
    // End of variables declaration//GEN-END:variables
   
    public void setCurrentReadingField(Float reading) {
        currentReadingField.setText(reading.toString());
    }

    public void setPreviousReadingField(Float previousReading) {
         previousReadingField.setText(previousReading.toString());
    }

    public void setTrendStatusField(String status) {
         trendStatusField.setText(status);
    }

    public void setRateTrendField(String rate) {
         rateTrendField.setText(rate);
    }

    public void setReadingHistoryArea(String message) {
         readingHistoryArea.append(message);
    }

    public JButton getBackToDashboardBtn() {
        return backToDashboardBtn;
    }
}
