/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import javax.swing.JButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Omar Ezzat
 */
public class DashboardView extends javax.swing.JFrame {

    /**
     * Creates new form DashboardView1
     */
    public DashboardView() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        currentTimeField = new javax.swing.JTextField();
        lblSystemStatus = new javax.swing.JLabel();
        systemStatusField = new javax.swing.JTextField();
        lblCurrentBloodSugar = new javax.swing.JLabel();
        currentBloodSugarField = new javax.swing.JTextField();
        lblLastComputedDose = new javax.swing.JLabel();
        lastComputedDoseField = new javax.swing.JTextField();
        lblCumulativeDailyDose = new javax.swing.JLabel();
        cumulativeDailyDoseField = new javax.swing.JTextField();
        lblReservoirStatus = new javax.swing.JLabel();
        reservoirStatusField = new javax.swing.JTextField();
        lblSystemMessages = new javax.swing.JLabel();
        scrollSystemMessages = new javax.swing.JScrollPane();
        systemMessageArea = new javax.swing.JTextArea();
        openBloodSugarBtn = new javax.swing.JButton();
        openDoseBtn = new javax.swing.JButton();
        refillReservoirBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cycleStatusField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        bufferMessages = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        capacityHolder = new javax.swing.JTextField();
        capacityError = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Insulin Pump Dashboard");
        setBackground(new java.awt.Color(44, 46, 47));
        setPreferredSize(new java.awt.Dimension(822, 590));
        setResizable(false);
        setSize(new java.awt.Dimension(822, 590));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblTitle.setText("Insulin Pump Dashboard");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 18, 250, -1));

        currentTimeField.setEditable(false);
        currentTimeField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        currentTimeField.setText("00:00:00");
        getContentPane().add(currentTimeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 104, 45));

        lblSystemStatus.setText("System Status");
        getContentPane().add(lblSystemStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 14, 100, 22));

        systemStatusField.setEditable(false);
        systemStatusField.setText("INACTIVE");
        getContentPane().add(systemStatusField, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 14, 78, -1));

        lblCurrentBloodSugar.setText("Current Blood Sugar");
        getContentPane().add(lblCurrentBloodSugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 121, 20));

        currentBloodSugarField.setEditable(false);
        currentBloodSugarField.setText("0.00");
        getContentPane().add(currentBloodSugarField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 80, -1));

        lblLastComputedDose.setText("Last Computed Dose");
        getContentPane().add(lblLastComputedDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 121, 19));

        lastComputedDoseField.setEditable(false);
        lastComputedDoseField.setText("0.00");
        getContentPane().add(lastComputedDoseField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 80, -1));

        lblCumulativeDailyDose.setText("Cumulative Daily Dose");
        getContentPane().add(lblCumulativeDailyDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 130, -1));

        cumulativeDailyDoseField.setEditable(false);
        cumulativeDailyDoseField.setText("0.00");
        getContentPane().add(cumulativeDailyDoseField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 80, -1));

        lblReservoirStatus.setText("Reservoir Capacity");
        getContentPane().add(lblReservoirStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 134, 110, -1));

        reservoirStatusField.setEditable(false);
        reservoirStatusField.setText("100.0 ml");
        reservoirStatusField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservoirStatusFieldActionPerformed(evt);
            }
        });
        getContentPane().add(reservoirStatusField, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 156, 117, -1));

        lblSystemMessages.setText("System Messages");
        getContentPane().add(lblSystemMessages, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        systemMessageArea.setEditable(false);
        systemMessageArea.setColumns(20);
        systemMessageArea.setLineWrap(true);
        systemMessageArea.setRows(5);
        systemMessageArea.setWrapStyleWord(true);
        scrollSystemMessages.setViewportView(systemMessageArea);

        getContentPane().add(scrollSystemMessages, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 299, 196));

        openBloodSugarBtn.setText("Blood Sugar View");
        getContentPane().add(openBloodSugarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, 138, 38));

        openDoseBtn.setText("Dose Delivery View");
        getContentPane().add(openDoseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 160, 38));

        refillReservoirBtn.setText("Refill Reservoir");
        refillReservoirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refillReservoirBtnActionPerformed(evt);
            }
        });
        getContentPane().add(refillReservoirBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 183, 36));

        jLabel1.setText("Cycle Status");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 70, 87, -1));

        cycleStatusField.setEditable(false);
        cycleStatusField.setText("Waiting");
        getContentPane().add(cycleStatusField, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 92, 117, -1));

        bufferMessages.setColumns(20);
        bufferMessages.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        bufferMessages.setRows(5);
        jScrollPane1.setViewportView(bufferMessages);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 320, 80));

        jLabel3.setText("Announcements");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 140, 24));

        capacityHolder.setText("0");
        capacityHolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capacityHolderActionPerformed(evt);
            }
        });
        capacityHolder.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                capacityHolderKeyTyped(evt);
            }
        });
        getContentPane().add(capacityHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 500, 80, -1));

        capacityError.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        capacityError.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(capacityError, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 530, 200, -1));

        jLabel2.setText("Reservoir capacity :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, 120, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refillReservoirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refillReservoirBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refillReservoirBtnActionPerformed

    private void reservoirStatusFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservoirStatusFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reservoirStatusFieldActionPerformed

    private void capacityHolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capacityHolderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_capacityHolderActionPerformed

    private void capacityHolderKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_capacityHolderKeyTyped
    char c = evt.getKeyChar();
    if (!(Character.isDigit(c) || c == java.awt.event.KeyEvent.VK_BACK_SPACE || c == java.awt.event.KeyEvent.VK_DELETE)) {
        evt.consume(); 
    }
    }//GEN-LAST:event_capacityHolderKeyTyped

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea bufferMessages;
    private javax.swing.JLabel capacityError;
    private javax.swing.JTextField capacityHolder;
    private javax.swing.JTextField cumulativeDailyDoseField;
    private javax.swing.JTextField currentBloodSugarField;
    private javax.swing.JTextField currentTimeField;
    private javax.swing.JTextField cycleStatusField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastComputedDoseField;
    private javax.swing.JLabel lblCumulativeDailyDose;
    private javax.swing.JLabel lblCurrentBloodSugar;
    private javax.swing.JLabel lblLastComputedDose;
    private javax.swing.JLabel lblReservoirStatus;
    private javax.swing.JLabel lblSystemMessages;
    private javax.swing.JLabel lblSystemStatus;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JButton openBloodSugarBtn;
    private javax.swing.JButton openDoseBtn;
    private javax.swing.JButton refillReservoirBtn;
    private javax.swing.JTextField reservoirStatusField;
    private javax.swing.JScrollPane scrollSystemMessages;
    private javax.swing.JTextArea systemMessageArea;
    private javax.swing.JTextField systemStatusField;
    // End of variables declaration//GEN-END:variables
    public void setCurrentTime(String time) {
        currentTimeField.setText(time);
    }
    public void setBloodSugar(Double value) {
        currentBloodSugarField.setText(String.valueOf(value));
    }

    public void setLastDose(Double dose) {
        lastComputedDoseField.setText(String.valueOf(dose.floatValue()));
    }


    public void setCumulativeDose(Double dose) {
        cumulativeDailyDoseField.setText(String.valueOf(dose.floatValue()));
    }

    public void setReservoir(Float value) {
        reservoirStatusField.setText(String.format("%.2f ml", value));
    }
    public void setSystemStatus(String status) {
        systemStatusField.setText(status);
    }

    public void addMessage(String msg) {
        systemMessageArea.append(msg + "\n");
    }
    public void setCapacityError(String msg) {
        capacityError.setText(msg);
    }
    public JTextArea getbufferMessages (){
        return bufferMessages;
    }
    public JTextField getCapacityHolder (){
        return capacityHolder;
    }
    public JButton getRefillReservoirBtn() {
        return refillReservoirBtn;
    }

    public JButton getOpenBloodSugarBtn() {
        return openBloodSugarBtn;
    }

    public JButton getOpenDoseBtn() {
        return openDoseBtn;
    }
    public void setCycleStatusField(String status) {
     cycleStatusField.setText(status);
    }
    
    
}