/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import javax.swing.JButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Omar Ezzat
 */
public class DashboardView extends javax.swing.JFrame {

    /**
     * Creates new form DashboardView1
     */
    public DashboardView() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblCurrentTime = new javax.swing.JLabel();
        currentTimeField = new javax.swing.JTextField();
        lblSystemStatus = new javax.swing.JLabel();
        systemStatusField = new javax.swing.JTextField();
        lblCurrentBloodSugar = new javax.swing.JLabel();
        currentBloodSugarField = new javax.swing.JTextField();
        lblLastComputedDose = new javax.swing.JLabel();
        lastComputedDoseField = new javax.swing.JTextField();
        lblCumulativeDailyDose = new javax.swing.JLabel();
        cumulativeDailyDoseField = new javax.swing.JTextField();
        lblReservoirStatus = new javax.swing.JLabel();
        reservoirStatusField = new javax.swing.JTextField();
        lblSystemMessages = new javax.swing.JLabel();
        scrollSystemMessages = new javax.swing.JScrollPane();
        systemMessageArea = new javax.swing.JTextArea();
        initializeBtn = new javax.swing.JButton();
        openBloodSugarBtn = new javax.swing.JButton();
        openDoseBtn = new javax.swing.JButton();
        refillReservoirBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cycleStatusField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        bufferMessages = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Insulin Pump Dashboard");
        setPreferredSize(new java.awt.Dimension(720, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(760, 560));

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblTitle.setText("Insulin Pump Dashboard");

        lblCurrentTime.setText("Current Time");

        currentTimeField.setEditable(false);
        currentTimeField.setText("00:00:00");

        lblSystemStatus.setText("System Status");

        systemStatusField.setEditable(false);
        systemStatusField.setText("INACTIVE");

        lblCurrentBloodSugar.setText("Current Blood Sugar");

        currentBloodSugarField.setEditable(false);
        currentBloodSugarField.setText("0.00");

        lblLastComputedDose.setText("Last Computed Dose");

        lastComputedDoseField.setEditable(false);
        lastComputedDoseField.setText("0.00");

        lblCumulativeDailyDose.setText("Cumulative Daily Dose");

        cumulativeDailyDoseField.setEditable(false);
        cumulativeDailyDoseField.setText("0.00");

        lblReservoirStatus.setText("Reservoir Status");

        reservoirStatusField.setEditable(false);
        reservoirStatusField.setText("100.0 ml");
        reservoirStatusField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservoirStatusFieldActionPerformed(evt);
            }
        });

        lblSystemMessages.setText("System Messages");

        systemMessageArea.setEditable(false);
        systemMessageArea.setColumns(20);
        systemMessageArea.setLineWrap(true);
        systemMessageArea.setRows(5);
        systemMessageArea.setWrapStyleWord(true);
        scrollSystemMessages.setViewportView(systemMessageArea);

        initializeBtn.setText("Initialize");
        initializeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initializeBtnActionPerformed(evt);
            }
        });

        openBloodSugarBtn.setText("Blood Sugar View");

        openDoseBtn.setText("Dose Delivery View");

        refillReservoirBtn.setText("Refill Reservoir");
        refillReservoirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refillReservoirBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Cycle Status");

        cycleStatusField.setEditable(false);
        cycleStatusField.setText("Waiting");

        bufferMessages.setColumns(20);
        bufferMessages.setRows(5);
        jScrollPane1.setViewportView(bufferMessages);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblCurrentBloodSugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblSystemStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(systemStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(currentBloodSugarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCurrentTime)
                                            .addComponent(currentTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCumulativeDailyDose)
                                    .addComponent(lblLastComputedDose)
                                    .addComponent(lastComputedDoseField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cumulativeDailyDoseField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblReservoirStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(reservoirStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblTitle)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(lblSystemMessages)
                                .addGap(110, 110, 110)))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cycleStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(111, 111, 111))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(openDoseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(initializeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(openBloodSugarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(refillReservoirBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(scrollSystemMessages, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLastComputedDose)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastComputedDoseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cycleStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCumulativeDailyDose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cumulativeDailyDoseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblReservoirStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reservoirStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCurrentTime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(currentTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSystemStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(systemStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCurrentBloodSugar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(currentBloodSugarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSystemMessages)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(initializeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(refillReservoirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(openDoseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(openBloodSugarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(126, 126, 126))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollSystemMessages, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(224, 224, 224))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initializeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initializeBtnActionPerformed

    }//GEN-LAST:event_initializeBtnActionPerformed

    private void refillReservoirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refillReservoirBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refillReservoirBtnActionPerformed

    private void reservoirStatusFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservoirStatusFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reservoirStatusFieldActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea bufferMessages;
    private javax.swing.JTextField cumulativeDailyDoseField;
    private javax.swing.JTextField currentBloodSugarField;
    private javax.swing.JTextField currentTimeField;
    private javax.swing.JTextField cycleStatusField;
    private javax.swing.JButton initializeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastComputedDoseField;
    private javax.swing.JLabel lblCumulativeDailyDose;
    private javax.swing.JLabel lblCurrentBloodSugar;
    private javax.swing.JLabel lblCurrentTime;
    private javax.swing.JLabel lblLastComputedDose;
    private javax.swing.JLabel lblReservoirStatus;
    private javax.swing.JLabel lblSystemMessages;
    private javax.swing.JLabel lblSystemStatus;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JButton openBloodSugarBtn;
    private javax.swing.JButton openDoseBtn;
    private javax.swing.JButton refillReservoirBtn;
    private javax.swing.JTextField reservoirStatusField;
    private javax.swing.JScrollPane scrollSystemMessages;
    private javax.swing.JTextArea systemMessageArea;
    private javax.swing.JTextField systemStatusField;
    // End of variables declaration//GEN-END:variables
    public void setCurrentTime(String time) {
        currentTimeField.setText(time);
    }
    public void setBloodSugar(Double value) {
        currentBloodSugarField.setText(String.valueOf(value));
    }

    public void setLastDose(Double dose) {
        lastComputedDoseField.setText(String.valueOf(dose.floatValue()));
    }


    public void setCumulativeDose(Double dose) {
        cumulativeDailyDoseField.setText(String.valueOf(dose.floatValue()));
    }

    public void setReservoir(Float value) {
        reservoirStatusField.setText(String.format("%.2f ml", value));
    }
    public void setSystemStatus(String status) {
        systemStatusField.setText(status);
    }

    public void addMessage(String msg) {
        systemMessageArea.append(msg + "\n");
    }
    public JTextArea getbufferMessages (){
        return bufferMessages;
    }
    public JButton getInitializeBtn() {
        return initializeBtn;
    }

    public JButton getRefillReservoirBtn() {
        return refillReservoirBtn;
    }

    public JButton getOpenBloodSugarBtn() {
        return openBloodSugarBtn;
    }

    public JButton getOpenDoseBtn() {
        return openDoseBtn;
    }
    public void setCycleStatusField(String status) {
     cycleStatusField.setText(status);
    }
    
    
}