/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import javax.swing.JButton;
import javax.swing.JTextField;
/**
 *
 * @author Omar Ezzat
 */
public class DoseDeliveryView extends javax.swing.JFrame {

    /**
     * Creates new form DoseDeliveryView
     */
    public DoseDeliveryView() {
        initComponents();
        backToDashboardBtn.addActionListener(e -> setVisible(false));
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblComputedDose = new javax.swing.JLabel();
        computedDoseField = new javax.swing.JTextField();
        lblMaxSingleDose = new javax.swing.JLabel();
        maxSingleDoseField = new javax.swing.JTextField();
        lblMaxDailyDose = new javax.swing.JLabel();
        maxDailyDoseField = new javax.swing.JTextField();
        lblCumulativeDailyDose = new javax.swing.JLabel();
        cumulativeDailyDoseField = new javax.swing.JTextField();
        lblDeliveryStatus = new javax.swing.JLabel();
        deliveryStatusField = new javax.swing.JTextField();
        backToDashboardBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dose Delivery Details");
        setMinimumSize(new java.awt.Dimension(760, 500));
        setPreferredSize(new java.awt.Dimension(760, 500));
        setResizable(false);

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblTitle.setText("Dose Delivery Monitoring");

        lblComputedDose.setText("Computed Dose");

        computedDoseField.setEditable(false);
        computedDoseField.setText("0.00");

        lblMaxSingleDose.setText("Max Single Dose");

        maxSingleDoseField.setEditable(false);
        maxSingleDoseField.setText("5.00");

        lblMaxDailyDose.setText("Max Daily Dose");

        maxDailyDoseField.setEditable(false);
        maxDailyDoseField.setText("25.00");

        lblCumulativeDailyDose.setText("Cumulative Daily Dose");

        cumulativeDailyDoseField.setEditable(false);
        cumulativeDailyDoseField.setText("0.00");

        lblDeliveryStatus.setText("Delivery Status");

        deliveryStatusField.setEditable(false);
        deliveryStatusField.setText("Delivered");

        backToDashboardBtn.setText("Back to Dashboard");
        backToDashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToDashboardBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblComputedDose, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(maxSingleDoseField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblMaxSingleDose, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(computedDoseField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMaxDailyDose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCumulativeDailyDose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDeliveryStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cumulativeDailyDoseField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maxDailyDoseField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deliveryStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(backToDashboardBtn)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTitle)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMaxDailyDose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maxDailyDoseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCumulativeDailyDose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cumulativeDailyDoseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDeliveryStatus))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblComputedDose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(computedDoseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblMaxSingleDose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maxSingleDoseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deliveryStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backToDashboardBtn)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backToDashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToDashboardBtnActionPerformed
       
    }//GEN-LAST:event_backToDashboardBtnActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToDashboardBtn;
    private javax.swing.JTextField computedDoseField;
    private javax.swing.JTextField cumulativeDailyDoseField;
    private javax.swing.JTextField deliveryStatusField;
    private javax.swing.JLabel lblComputedDose;
    private javax.swing.JLabel lblCumulativeDailyDose;
    private javax.swing.JLabel lblDeliveryStatus;
    private javax.swing.JLabel lblMaxDailyDose;
    private javax.swing.JLabel lblMaxSingleDose;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField maxDailyDoseField;
    private javax.swing.JTextField maxSingleDoseField;
    // End of variables declaration//GEN-END:variables
    public void setComputedDoseField(Float dose) {
         computedDoseField.setText(dose.toString());
    }

    public void setDoseDeliveryStatus(String status) {
        deliveryStatusField.setText(status);
    }

    public void setMaxSingleDoseField(Float maxDose) {
         maxSingleDoseField.setText(maxDose.toString());
    }

    public void setMaxDailyDoseField(Float maxDaily ) {
        maxDailyDoseField.setText(maxDaily.toString());
    }

    public void setCumulativeDailyDoseField(Float cumilative) {
         cumulativeDailyDoseField.setText(cumilative.toString());
    }

    public JButton getBackToDashboardBtn() {
        return backToDashboardBtn;
    }
}
