/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import javax.swing.JButton;
import javax.swing.JTextField;
/**
 *
 * @author Omar Ezzat
 */
public class DoseDeliveryView extends javax.swing.JFrame {

    /**
     * Creates new form DoseDeliveryView
     */
    public DoseDeliveryView() {
        initComponents();
        backToDashboardBtn.addActionListener(e -> setVisible(false));
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblComputedDose = new javax.swing.JLabel();
        computedDoseField = new javax.swing.JTextField();
        lblMaxSingleDose = new javax.swing.JLabel();
        maxSingleDoseField = new javax.swing.JTextField();
        lblMaxDailyDose = new javax.swing.JLabel();
        maxDailyDoseField = new javax.swing.JTextField();
        lblCumulativeDailyDose = new javax.swing.JLabel();
        cumulativeDailyDoseField = new javax.swing.JTextField();
        lblDeliveryStatus = new javax.swing.JLabel();
        deliveryStatusField = new javax.swing.JTextField();
        backToDashboardBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dose Delivery Details");
        setMinimumSize(new java.awt.Dimension(565, 340));
        setSize(new java.awt.Dimension(556, 321));
        getContentPane().setLayout(null);

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblTitle.setText("Dose Delivery Monitoring");
        getContentPane().add(lblTitle);
        lblTitle.setBounds(140, 42, 254, 25);

        lblComputedDose.setText("Computed Dose");
        getContentPane().add(lblComputedDose);
        lblComputedDose.setBounds(6, 126, 116, 16);

        computedDoseField.setEditable(false);
        computedDoseField.setText("0.00");
        getContentPane().add(computedDoseField);
        computedDoseField.setBounds(140, 123, 75, 22);

        lblMaxSingleDose.setText("Max Single Dose");
        getContentPane().add(lblMaxSingleDose);
        lblMaxSingleDose.setBounds(312, 166, 120, 16);

        maxSingleDoseField.setEditable(false);
        maxSingleDoseField.setText("5.00");
        getContentPane().add(maxSingleDoseField);
        maxSingleDoseField.setBounds(446, 163, 89, 22);

        lblMaxDailyDose.setText("Max Daily Dose");
        getContentPane().add(lblMaxDailyDose);
        lblMaxDailyDose.setBounds(312, 206, 128, 16);

        maxDailyDoseField.setEditable(false);
        maxDailyDoseField.setText("25.00");
        getContentPane().add(maxDailyDoseField);
        maxDailyDoseField.setBounds(446, 203, 89, 22);

        lblCumulativeDailyDose.setText("Cumulative Daily Dose");
        getContentPane().add(lblCumulativeDailyDose);
        lblCumulativeDailyDose.setBounds(6, 202, 128, 16);

        cumulativeDailyDoseField.setEditable(false);
        cumulativeDailyDoseField.setText("0.00");
        cumulativeDailyDoseField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cumulativeDailyDoseFieldActionPerformed(evt);
            }
        });
        getContentPane().add(cumulativeDailyDoseField);
        cumulativeDailyDoseField.setBounds(140, 199, 75, 22);

        lblDeliveryStatus.setText("Delivery Status");
        getContentPane().add(lblDeliveryStatus);
        lblDeliveryStatus.setBounds(10, 160, 100, 30);

        deliveryStatusField.setEditable(false);
        deliveryStatusField.setText("Delivered");
        getContentPane().add(deliveryStatusField);
        deliveryStatusField.setBounds(140, 163, 100, 28);

        backToDashboardBtn.setText("Back to Dashboard");
        backToDashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToDashboardBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backToDashboardBtn);
        backToDashboardBtn.setBounds(203, 265, 150, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backToDashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToDashboardBtnActionPerformed
       
    }//GEN-LAST:event_backToDashboardBtnActionPerformed

    private void cumulativeDailyDoseFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cumulativeDailyDoseFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cumulativeDailyDoseFieldActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToDashboardBtn;
    private javax.swing.JTextField computedDoseField;
    private javax.swing.JTextField cumulativeDailyDoseField;
    private javax.swing.JTextField deliveryStatusField;
    private javax.swing.JLabel lblComputedDose;
    private javax.swing.JLabel lblCumulativeDailyDose;
    private javax.swing.JLabel lblDeliveryStatus;
    private javax.swing.JLabel lblMaxDailyDose;
    private javax.swing.JLabel lblMaxSingleDose;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField maxDailyDoseField;
    private javax.swing.JTextField maxSingleDoseField;
    // End of variables declaration//GEN-END:variables
    public void setComputedDoseField(Float dose) {
         computedDoseField.setText(dose.toString());
    }

    public void setDoseDeliveryStatus(String status) {
        deliveryStatusField.setText(status);
    }

    public void setMaxSingleDoseField(Float maxDose) {
         maxSingleDoseField.setText(maxDose.toString());
    }

    public void setMaxDailyDoseField(Float maxDaily ) {
        maxDailyDoseField.setText(maxDaily.toString());
    }

    public void setCumulativeDailyDoseField(Float cumilative) {
         cumulativeDailyDoseField.setText(String.format("%.2f ml", cumilative));
    }

    public JButton getBackToDashboardBtn() {
        return backToDashboardBtn;
    }
}
